[package]
name = "makemake"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Uppal"]
repository = "https://github.com/ethanuppal/makemake"
description = "Library for building Makefiles programmatically"
license-file = "LICENSE"

[dependencies]
insta = "1.39.0"
paste = "1.0.15"
